### PR TITLE
initramfs needs network configured per NBFT before nvme-cli can establish connection (SLE15-SP5:GA)

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
Ref: jsc#PED-1449

CC: @mwilck

### CODE REVIEW

**Comment by tblume** [comment]
Hm, that looks like a feature but  I couldn't find these patches upstream.
Antonio, how are we currently dealing with the upstream-first policy?
Is it first submitted to openSUSE git and then to upstream or should it be submitted to upstream git first?

**Comment by aafeijoo-suse** [comment]
> Hm, that looks like a feature but I couldn't find these patches upstream. Antonio, how are we currently dealing with the upstream-first policy? Is it first submitted to openSUSE git and then to upstream or should it be submitted to upstream git first?

PM made an exception in this case, read comments in PED-967 (epic of PED-1449 impl task). This must be shipped as "Technology Preview" in SLE15-SP5 until it's accepted upstream (cut-off for GA: 2023-01-25). Same exception applies for libnvme and nvme-cli.

**Comment by tblume** [comment]
Ok, thanks

**Review by tblume — APPROVED** [review]
LGTM

**Comment by aafeijoo-suse** [comment]
Thanks Thomas.

JFYI, the upstream submission will be made from the Timberland SIG: https://github.com/timberland-sig/dracut/pull/1

**Pull request merged**
