### PR TITLE
nvmf / IPv6 related fixes for SLE15-SP5

### PR DESCRIPTION
**Pull request by mwilck**
Fixes for IPv6 issues that were found in NVMeoF boot testing.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

This is equivalent to the update of the usptream PR https://github.com/dracutdevs/dracut/pull/2184 that I did today (91e1ee9).

### CODE REVIEW

**Review by tblume — COMMENTED** [review]
Hm, calling the nvmf-autoconnect.sh script in multiple stages might cause quite a delay until the boot finally succeeds or fails.
@mwilck  how long was the the delay in your tests in the worst case?

**Comment by mwilck** [comment]
> Hm, calling the nvmf-autoconnect.sh script in multiple stages might cause quite a delay until the boot finally succeeds or fails. @mwilck how long was the the delay in your tests in the worst case?

In my testing, `nvme connect-nbft` has always been very fast. What takes long is the network setup. But of course I can't prove that under certain condition the connect command itself might run into timeouts.


Note that (in the current code) I haven't installed a scipt in the main "initqueue" which is called every second.
The logic I implemented is the same that's used for iSCSI, using the "online", "settled", and "timeout" hooks. In my testing, 90% of the time the script run in the "online" hook succeeds immediately. "timeout" is just the last resort, and will never be reached except in already problematic situations. "settled" will be called a few times, but not very often.

**Comment by tblume** [comment]
Ok, thanks Martin.
LGTM

**Comment by mwilck** [comment]
Pushed shfmt fixes.

**Comment by mwilck** [comment]
Fixed commit message as remarked by @aafeijoo-suse on dracutdevs/dracut/pull/2184

**Comment by mwilck** [comment]
What's holding back this PR? It causes almost boot failure for NVMeoF / IPv6 in static configurations. There's practically no way to recover, the system just halts hard.

**Comment by aafeijoo-suse** [comment]
> What's holding back this PR? It causes almost boot failure for NVMeoF / IPv6 in static configurations. There's practically no way to recover, the system just halts hard.

I thought we wanted to wait until the upstream code is accepted, because the basic tech preview feature is already there, but maybe I misunderstood. Do we need to include this in 15-SP5 GM?

**Comment by mwilck** [comment]
>  Do we need to include this in 15-SP5 GM?

IMO, yes. These are fixes for the code we already have in beta. 
True, it remains problematic that upstream acceptance is going slowly.
But that's not related to this PR.

**Pull request merged**
