### PR TITLE
Backport upstream fixes to 059 (2nd batch)

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
OBS:
- Project: https://build.opensuse.org/package/show/home:afeijoo:branches:openSUSE:Factory:059-upstream-fixes-2/dracut
- x86_64 repo: https://download.opensuse.org/repositories/home:/afeijoo:/branches:/openSUSE:/Factory:/059-upstream-fixes-2/standard/

### CODE REVIEW

**Review by tblume — COMMENTED** [review]
Hm, I'd be surprised if wicked is removed from the SLE15 versions.
So this patch is probably not not for 15SP6?

**Comment by aafeijoo-suse** [comment]
> Hm, I'd be surprised if wicked is removed from the SLE15 versions. So this patch is probably not not for 15SP6?

This is not about `wicked`, which is still used in our patched `network-legacy` module, but about the `network-wicked` module, see: https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/Y6L3HOZY7EZYCVVIK3J6VEKMNCAEHCTO/

We should not ship it with SLE15-SP6, the question is whether dropping it only for SLE next month or now from factory (and do not wait indefinitely for dracut-060, the deprecation notice was sent 5 months ago). Same question applies to the `systemd-rfkill` module (which will not work with systemd-v254: https://github.com/systemd/systemd/commit/49c55abc).

**Comment by tblume** [comment]
> This is not about `wicked`, which is still used in our patched `network-legacy` module, but about the `network-wicked` module, see: https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/Y6L3HOZY7EZYCVVIK3J6VEKMNCAEHCTO/
> 
> We should not ship it with SLE15-SP6, the question is whether dropping it only for SLE next month or now from factory (and do not wait indefinitely for dracut-060, the deprecation notice was sent 5 months ago). Same question applies to the `systemd-rfkill` module (which will not work with systemd-v254: [systemd/systemd@49c55abc](https://github.com/systemd/systemd/commit/49c55abc)).

Ah ok, yes, then it makes sense to drop these modules from factory now.
No need to wait for dracut-060.

**Review by tblume — APPROVED** [review]
LGTM

**Pull request merged**
