### PR TITLE
ci(suse): set zstd as default compression

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
This pull request sets zstd as default compression.

Reference: jsc#SLE-20248

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by tblume** [comment]
@mwilck ok for you?

**Review by mwilck — COMMENTED** [review]
I have seen that upstream behaves this way. I'm not sure it makes sense on SLE. IMO it would make more sense to fall back to xz compression, which was the default on SLE before.

**Comment by aafeijoo-suse** [comment]
@mwilck, I think you should update the Jira task so everyone is notified of your current thoughts, because this PR was made using the parameters you requested 3 weeks ago.

**Comment by mwilck** [comment]
> @mwilck, I think you should update the Jira task so everyone is notified of your current thoughts, because this PR was made using the parameters you requested 3 weeks ago.

I fail to see in which way my comments in this PR contradict what I recommended in Jira. I only commented on the fallback code, and on the `Requires:` in the spec file. Both are technical details that haven't been discussed in Jira.

**Comment by aafeijoo-suse** [comment]
Sorry, I misunderstood your comment. Yes, the fallback option could be arguable, I don't know which option is better.
But the other thing, if we want to set zstd as default, shouldn't we require it in the spec file?

**Comment by mwilck** [comment]
Hm, I made a mistake too. I was confused by the fallback in case the kernel didn't support **zstd**. Obviously, the same fallback could also be used if **zstd** wasn't installed in the first place, but the upstream code doesn't do that AFAICS. We could add the test of course.

distro maintainers typically dislike hard` Requires:`, because they tend to blow up the distribution. We should raise this question in Jira. We must either add the Requires:, or implement a fallback for cases where zstd is not available.

**Comment by aafeijoo-suse** [comment]
So, it seems the final decision is:
```
Recommends:     xz
Requires:       zstd
```
This should be ready to submit to factory.

**Pull request merged**
