### PR TITLE
chore(suse): update url in spec

### PR DESCRIPTION
**Pull request by LaszloGombos**

### CODE REVIEW

**Comment by tblume** [comment]
Hm, the url https://dracut.wiki.kernel.org/ is actually the same upstream:

https://github.com/dracutdevs/dracut/blob/master/pkgbuild/dracut.spec

Laszlo is it planned to change it there too?

**Comment by LaszloGombos** [comment]
See https://github.com/dracutdevs/dracut/issues/1837.

**Review by tblume — APPROVED** [review]
LGTM, following https://github.com/dracutdevs/dracut/issues/1837

**Review by aafeijoo-suse — APPROVED** [review]
ok, thanks!

**Pull request merged**
