### PR TITLE
network-manager backports

### PR DESCRIPTION
**Pull request by Vogtinator**
Fix excessive logging.

### CODE REVIEW

**Comment by aafeijoo-suse** [comment]
Hi Fabian, what's the main destination of this backport, Tumbleweed or Leap/SLE? If it's TW, it will be automatically included with the upgrade to 056. The 055 branch will be used for Leap15.4/SLE15-SP4 maintenance updates.

**Comment by Vogtinator** [comment]
TW. TW is still on 055 FWICT, and I don't know when 056 will arrive.

**Comment by aafeijoo-suse** [comment]
> TW. TW is still on 055 FWICT, and I don't know when 056 will arrive.

Upstream 056 has already been released, we are working on the merge for factory.

**Comment by Vogtinator** [comment]
> > TW. TW is still on 055 FWICT, and I don't know when 056 will arrive.
> 
> Upstream 056 has already been released, we are working on the merge for factory.

What's the ETA for that? If it's >1week, can you merge and submit this before?

**Comment by aafeijoo-suse** [comment]
> What's the ETA for that? If it's >1week, can you merge and submit this before?

If our remaining tests are ok, the submission will be done in less than 1 week. But we can keep this PR open if that does not happen.

**Comment by aafeijoo-suse** [comment]
Fix already merged in TW with the update to 056.

**Pull request closed without merging**
