### PR TITLE
Repair POSIX compliance

### PR DESCRIPTION
**Pull request by tacerus**
Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>

Hi,

upon trying to build the openSUSE fork of dracut using `make check clean`, two errors occurred:

```
modules.d/35network-legacy/ifup.sh contains [[
modules.d/45ifcfg/write-ifcfg-suse.sh contains echo -n
```

This patch restores compatibility with the upstream POSIX compliance check.

Do I need to take care of any SUSE related version bumping / changelogging for patches here?

Best,
Georg

### CODE REVIEW

**Review by aafeijoo-suse — APPROVED** [review]
LGTM

**Comment by aafeijoo-suse** [comment]
Please split the changes into 2 different commits, and follow https://github.com/openSUSE/dracut/blob/SUSE/056/docs/HACKING.md#commit-messages

- fix(network-legacy): repair POSIX compliance
- fix(ifcfg): repair POSIX compliance

**Comment by tacerus** [comment]
Sorry for having missed that and thanks for the link!

I now replaced the commits with appropriately titled ones!

**Comment by aafeijoo-suse** [comment]
> Sorry for having missed that and thanks for the link!
> 
> I now replaced the commits with appropriately titled ones!

Thanks!

**Pull request merged**
