### PR TITLE
fix(nvmf): honor config.json in check()

### PR DESCRIPTION
**Pull request by mwilck**
Fixes from [Upstream PR](https://github.com/dracutdevs/dracut/pull/2184)

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by aafeijoo-suse** [comment]
Sorry Martin, somehow I overlooked this PR... Do we really need to check `config.json` in the SLE15-SP5 code? It's not anywhere in this version of the `nvmf` module (I know the upstream version is different).

**Comment by mwilck** [comment]
I would say so ... nvme-cli definitely supports `config.json` in SP5. In SP4, too, IIRC.

**Comment by aafeijoo-suse** [comment]
But, although it's supported, it's not being installed in the initrd or used in the `nvmf-autoconnect.sh` script, so there may be a situation where the `nvmf` module can be installed because `config.json` exists because of this change, but it will not be used anywhere.

```sh
SLE-15-SP5_Update> grep -r -n --color -e config.json -e discovery.conf modules.d/95nvmf/
modules.d/95nvmf/nvmf-autoconnect.sh:23:if [ -f /etc/nvme/discovery.conf ] && [ $NVMF_HOSTNQN_OK ]; then
modules.d/95nvmf/nvmf-autoconnect.sh:24:    # prio 3: discovery.conf from initrd
modules.d/95nvmf/module-setup.sh:45:            if [ ! -f /etc/nvme/discovery.conf ] && ! has_nbft; then
modules.d/95nvmf/module-setup.sh:143:    inst_simple "/etc/nvme/discovery.conf"
modules.d/95nvmf/parse-nvmf-boot-connections.sh:276:            rm /etc/nvme/discovery.conf
modules.d/95nvmf/parse-nvmf-boot-connections.sh:288:        echo "--transport=$trtype --traddr=$traddr --host-traddr=$hosttraddr" >> /etc/nvme/discovery.conf
modules.d/95nvmf/parse-nvmf-boot-connections.sh:290:        echo "--transport=$trtype --traddr=$traddr --host-traddr=$hosttraddr --trsvcid=$trsvcid" >> /etc/nvme/discovery.conf
```


```sh
master> grep -r -n --color -e config.json -e discovery.conf modules.d/95nvmf/
modules.d/95nvmf/module-setup.sh:45:            && [ ! -f /etc/nvme/discovery.conf ] \
modules.d/95nvmf/module-setup.sh:46:            && [ ! -f /etc/nvme/config.json ] && ! has_nbft; then
modules.d/95nvmf/module-setup.sh:143:    inst_simple "/etc/nvme/discovery.conf"
modules.d/95nvmf/module-setup.sh:144:    inst_simple "/etc/nvme/config.json"
modules.d/95nvmf/nvmf-autoconnect.sh:38:if [ -f /etc/nvme/discovery.conf ] || [ -f /etc/nvme/config.json ] \
modules.d/95nvmf/parse-nvmf-boot-connections.sh:227:    rm -f /etc/nvme/discovery.conf /etc/nvme/config.json
modules.d/95nvmf/parse-nvmf-boot-connections.sh:281:            rm -f /etc/nvme/discovery.conf /etc/nvme/config.json
modules.d/95nvmf/parse-nvmf-boot-connections.sh:293:        echo "--transport=$trtype --traddr=$traddr --host-traddr=$hosttraddr" >> /etc/nvme/discovery.conf
modules.d/95nvmf/parse-nvmf-boot-connections.sh:295:        echo "--transport=$trtype --traddr=$traddr --host-traddr=$hosttraddr --trsvcid=$trsvcid" >> /etc/nvme/discovery.conf
```

**Comment by mwilck** [comment]
> But, although it's supported, it's not being installed in the initrd or used in the `nvmf-autoconnect.sh` script

Right. The upstream commit f07117d contains the hook for `install()` (no idea why it has been lost here), The upstream NBFT commit (b490f6f) contains the hunks for `config.json` support in the initrd itself.

I'll update this PR.

**Comment by mwilck** [comment]
Pushed the update now, sorry it took so long.

**Review by aafeijoo-suse — APPROVED** [review]
Thanks Martin, no problem, I missed it first.
I created bsc#1215578 to handle this.

**Pull request merged**
