### PR TITLE
feat(multipath): warn if included with no multipath devices and no user conf (bsc#1069169)

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
The multipath module is always included in no-hostonly mode, but including it in the initramfs might activate multipath on the root device, which could be undesirable. This behavior can be manually fixed by explicitly excluding the root device from multipath in /etc/multipath.conf.

Therefore, issue a warning in no-hostonly mode, if there is no multipath device and the user has not configured multipath.

CC: @mwilck

### CODE REVIEW

**Comment by tblume** [comment]
Hm, not sure if addressing this in dracut is really necessary.

Normally, the exclusion of local disks is already done by multipath itself.
The multipath internal config table has:

-->
blacklist {
        devnode "!^(sd[a-z]|dasd[a-z]|nvme[0-9])"
--<

 with the exception of devices that show properties of a remote storage:

-->
blacklist_exceptions {
        property "(SCSI_IDENT_|ID_WWN)"
}
--<

So, local disks should never get multipathed, while remote storage disks should be multipathed, because there are usually multiple paths.
@mwilck what is your opinion?

**Comment by mwilck** [comment]
No, `SCSI_IDENT_*`  is set for local disks, too. The SATA disk of my laptop:
```
 udevadm info /dev/sda|grep SCSI_ID
E: SCSI_IDENT_SERIAL=FJ63N456110303C1E
E: SCSI_IDENT_LUN_VENDOR=FJ63N456110303C1E
E: SCSI_IDENT_LUN_T10=ATA_SK_hynix_SC300_M.2_2280_512GB_FJ63N456110303C1E
E: SCSI_IDENT_LUN_ATA=SK_hynix_SC300_M.2_2280_512GB_FJ63N456110303C1E
```

**Comment by tblume** [comment]
> udevadm info /dev/sda|grep SCSI_ID

Hm, ideed, any idea why?
It doesn't make sense to me to exclude local disks from the blacklist.

**Comment by mwilck** [comment]
> It doesn't make sense to me to exclude local disks from the blacklist.

I don't grok what you want to say here. This is normal behavior.  The `SCSI_IDENT_` logic has nothing to do with local or remote disks. It's purpose is to exclude dumb legacy SCSI drives that have no useful ID at all.

We can't detect from these properties whether a disk is local or not. I'd be happy if it was possible, but it's not.

**Comment by tblume** [comment]
> > It doesn't make sense to me to exclude local disks from the blacklist.
> 
> I don't grok what you want to say here. This is normal behavior. The `SCSI_IDENT_` logic has nothing to do with local or remote disks. It's purpose is to exclude dumb legacy SCSI drives that have no useful ID at all.
> 
> We can't detect from these properties whether a disk is local or not. I'd be happy if it was possible, but it's not.

Ah ok, thanks for the background.
So, I've misinterpreted the internal blacklist.
It is not for excluding local disks.

Antonio, that means your pr is LGTM.

**Review by tblume — APPROVED** [review]

**Pull request merged**
