### PR TITLE
Remove /sbin/installkernel script from dracut package

### PR DESCRIPTION
**Pull request by mwilck**
Nowadays, /sbin/installkernel is only used by developers who compile their
own kernels on the target system. It doesn't need to be part of dracut
any more.

## Checklist
- [ ] I have tested it locally
- [ x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

See recent discussion on SUSE kernel ML ("Making Secure Boot kernels easier")

### CODE REVIEW

**Comment by mwilck** [comment]
@tblume , please have a look.

**Comment by mwilck** [comment]
re-pushed to satisfy commisery bot.

**Comment by mwilck** [comment]
This PR depends on the decision made for https://github.com/jeffmahoney/kernel-install-tools. @jeffmahoney, can you notify us here when kernel-install-tools enters Factory (or SLE)?

**Review by tblume — COMMENTED** [review]
LGTM

**Comment by mwilck** [comment]
The tools have moved to [kernel-install-tools](https://github.com/jeffmahoney/kernel-install-tools), available from [home:jeffmahoney:Kernel](https://build.opensuse.org/package/show/home:jeff_mahoney:Kernel/kernel-install-tools).

We had [originally agreed](https://github.com/openSUSE/dracut/pull/85#issuecomment-913645176) to wait until a final decision on inclusion of kernel-install-tools before merging this. But I suppose this was in danger of getting stalled. Now we've got motion again :-)

@jeffmahoney, is anything preventing us from pushing k-i-t to Factory?

**Pull request merged**
